### ISSUE TITLE
blsimpv() reaches max iterations when vega approaches 0, resulting in NaN implied volatility.

### ISSUE THREAD

**Issue by Forty-Tw0** [rcalxrc08/FinancialToolbox.jl#21]
On an ITM option such as,
`blsimpv(4753.63, 4085.0, 0.0525, 0.13870843734533175, 701.3994, 0.0, true)`

In `blprice_and_vega()`, the `normpdf(d1) == 0.0`, which results in `vega == 0.0`
Then in `iter_blimpv()` `σ_new = max(σ + (price - cur_price) / cur_vega, eps_adj)` becomes `Inf`, and `fixed_point_blimpv()` reaches the max number of iterations and returns `NaN` for implied volatility.

My workaround in iter_blimpv() is to stop the iterations once vega becomes 0.
```julia
    if cur_vega == 0.0
        return σ
    end
```

**Comment by rcalxrc08** [comment]
Hi! Thank you a lot!!! I will add a test exactly for this example.
Soon I will submit a fix or in case I will revert to a safer Brent method.

**Comment by rcalxrc08** [comment]
it is solved on master. I am going to cut a release soon.

**Comment by rcalxrc08** [comment]
Solved on 0.6.0
